### ISSUE TITLE
Virus total flags the exe

### ISSUE THREAD

**Issue by ma-karai** [zkxs/simple-crosshair-overlay#18]
![image](https://github.com/zkxs/simple-crosshair-overlay/assets/17119942/1408c330-2dd2-4543-bf27-d6db278b9b2b)

**Comment by zkxs** [comment]
Here's [the link the Virustotal scan](https://www.virustotal.com/gui/file/7d7f3ee060d6e47a34d5cea39a45807dc628191a4174f9109b2aa5144c2db5ae/detection).

While I appreciate the heads-up, there's not much I can do about false positives in some small percentage of antivirus engines, especially when that Bkav engine straight up says it was an AI detection (so no human on earth knows why it got flagged). I imagine it's mad that I capture keyboard input, but who knows. Maybe it's mad that this isn't typical assembly, on account of coming from Rust versus C/C++. Or maybe it's angry that I'm not paying the protection money for an Authenticode signing cert.

Now for the elephant in the room: what if I'm evil, and have hidden some nefarious payload in that binary? In that case I suggest you compile the binary yourself via either `cargo install` or `cargo build` as I've documented in the readme.

If you think there's some further action I should take here please feel free to reopen the issue, but I really don't think there's anything I can do about it.

**Comment by ma-karai** [comment]
Alright, just thought you might be interested 👯
